# Generated by Django 2.2.5 on 2019-09-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='name_lecture',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
