# Generated by Django 2.2.5 on 2019-09-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20190918_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lecture',
        ),
        migrations.AddField(
            model_name='lecture',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Course.Course'),
            preserve_default=False,
        ),
    ]
