# Generated by Django 2.2.5 on 2019-09-18 09:17

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0006_auto_20190918_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, verbose_name='Видео'),
        ),
    ]
